# Generated by Django 5.0 on 2023-12-13 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApplication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='author',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='image',
        ),
    ]
